### PR TITLE
Dependency: Support calling your changlog CHANGES

### PR DESCRIPTION
**Pull request by olleolleolle**
Here's an example of such a changelog: https://github.com/twilio/twilio-ruby/blob/master/CHANGES.md

See https://github.com/gocardless/bump/issues/105

### CODE REVIEW

**Comment by hmarr** [comment]
👍 thanks!

Your username is 👌, by the way.

**Comment by olleolleolle** [comment]
Thanks for merging!

How about this one: 

```ruby
file = files.find { |f| CHANGELOG_NAMES.any? { |w| f.name =~ /\A#{w}/i } }
```

We want to match _the beginning of the filename_ only.

**Comment by hmarr** [comment]
Good point, and we probably also want to check for a period after the name:

```ruby
file = files.find { |f| CHANGELOG_NAMES.any? { |w| f.name =~ /\A#{w}\./i } }
```

Fancy putting a PR in? If not, let me know and I'll make the change.

**Comment by olleolleolle** [comment]
In a bus in traffic atm - 

Some projects have no suffix at all! NEWS or CHANGES & cetera

**Comment by hmarr** [comment]
Yeah, I guess so. Would be nice to avoid picking up `newspaper.md` etc, though. Whitelisting extensions is a bit annoying, but possibly worthwhile to avoid matching on `news.rb`, etc. If we go down that route, [this whitelist](https://github.com/github/markup/blob/master/README.md#markups) could be a good starting point.

Something along the lines of:

```ruby
EXTENSIONS = [nil, "md", "markdown", ...]
...
base_name, extension = f.name.downcase.split(".")
CHANGELOG_NAMES.include?(base_name) && EXTENSIONS.include?(extension)

**Comment by olleolleolle** [comment]
@hmarr I'd be using Pathname, my friend in all these cases, to do the filebame munging/splitting.

**Comment by hmarr** [comment]
TIL about `#extname`, thanks.

**Pull request merged**
