### PR TITLE
Move reusable code into lib/bump

### PR DESCRIPTION
**Pull request by hmarr**
This will make it easy to make Bump work as a library, as well as an
app.

The next step is either to split the core (library) code and the app
code (workers & sidekiq UI) into separate codebases, or to make this
repo work for both purposes (by adding a gemspec).

Currently these changes are purely organisational, and everything works
as it did previously.

### CODE REVIEW

**Comment by greysteil** [comment]
@hmac - can you take a look? Everything runs 👌  locally.

**Comment by hmac** [comment]
Big 😬 
This kind of PR is sooo much easier to review if you do the file moving and the file changes in separate commits.

**Comment by hmarr** [comment]
@hmac done :-)

**Comment by hmac** [comment]
looks good :+1:

**Pull request merged**
